### ISSUE TITLE
Set up basic LavaPlayer functionality

### ISSUE THREAD

**Issue by MitchellTFord** [MitchellTFord/discord-bot#38]
Depends on #29 

### MVP Acceptance Criteria:
- The bot should join the user's current voice channel and play music when the following command is invoked with some valid `YOUTUBE_URL`:
```
!play YOUTUBE_URL
```
- The bot should leave the voice channel it's in when the following command is invoked:
```
!stop
```

### Future Functionality (suggested by @nickvichai):
- The bot should join the user's current voice channel when the following command is invoked:
```
!join
```
- The bot should leave its current voice channel and stop playback when the following command is invoked. If this command is added, it may make sense for the `stop` command to not make the bot leave the voice channel
```
!leave
```

**Comment by MitchellTFord** [comment]
This issue needs more information, but anyone who needs work can get started on it now

**Comment by AustinWongParker** [comment]
Maybe I take this one? This one kinda sucks tho cause you would need access to the bot directly on discord and the API. Isn't Will in charge of that?

**Comment by MitchellTFord** [comment]
You only need access to the bot for testing. You can always make your own bot account if you want to. @AustinWongParker 

IDK if @LiangZhang21 and/or @nickvichai want to work on this as well.

**Comment by AustinWongParker** [comment]
That makes sense

**Comment by nickvichai** [comment]
Additional and recommended acceptance criteria:

- The bot should be invoked to join a user's voice channel (message an error if user isn't in a voice channel):
```
!join
```
- The bot should then be given a command to play music with a valid URL (message an error if URL is invalid or if no data was retrieved from URL:
```
!play URL
```
- The bot should have a command to stop playback:
```
!stop
```
- The bot should have a command to leave the voice channel
```
!leave
```
